version: "3.7"
services:
  web:
    image: nginx
    volumes:
      - nginx.vol:/usr/share/nginx/html
    networks:
     - traefik-public
    deploy:
      replicas: 5
      labels:
        - "traefik.enable=true"
        - "traefik.http.routers.docker.rule=Host(`sample.emma.local`)"
        - "traefik.http.routers.docker.entrypoints=web"
        - "traefik.http.services.docker.loadbalancer.server.port=80"

networks:
  traefik-public:
    external: true


volumes:
  nginx.vol:
    driver: local
    driver_opts:
      type: nfs
      o: addr=172.21.5.87,rw
      device: ":/nfsdata/nginx_web"
